# Generated by Django 5.0.6 on 2024-08-06 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, null=True)),
                (
                    "nome_social",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nome_mae", models.CharField(max_length=100, null=True)),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("Masculino", "Masculino"),
                            ("Feminino", "Feminino"),
                            ("Intersexo", "Intersexo"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("genero", models.CharField(max_length=50, null=True)),
                ("data_nascimento", models.DateField(null=True)),
                (
                    "raca",
                    models.CharField(
                        choices=[
                            ("Branca", "Branca"),
                            ("Preta", "Preta"),
                            ("Parda", "Parda"),
                            ("Amarela", "Amarela"),
                            ("Indígena", "Indígena"),
                            ("Sem Informação", "Sem Informação"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("nacionalidade", models.CharField(max_length=50, null=True)),
                ("cidade_nascimento", models.CharField(max_length=50, null=True)),
                ("uf_nascimento", models.CharField(max_length=2, null=True)),
                ("data_naturalizacao", models.DateField(blank=True, null=True)),
                ("pais_nascimento", models.CharField(blank=True, max_length=50)),
                (
                    "numero_passaporte",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "pais_emissao",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("data_emissao", models.DateField(blank=True, null=True)),
                ("data_validade", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(max_length=200, null=True)),
                (
                    "tipo_telefone",
                    models.CharField(
                        choices=[
                            ("Residencial", "Residencial"),
                            ("Celular", "Celular"),
                            ("Comercial", "Comercial"),
                            ("Outro", "Outro"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("ddd", models.CharField(max_length=3, null=True)),
                ("telefone", models.CharField(max_length=200, null=True)),
                ("tipo_logradouro", models.CharField(max_length=50, null=True)),
                ("nome_logradouro", models.CharField(max_length=200, null=True)),
                ("numero_logradouro", models.CharField(max_length=10, null=True)),
                ("complemento_logradouro", models.CharField(max_length=200, null=True)),
                ("bairro", models.CharField(max_length=100, null=True)),
                ("cidade", models.CharField(max_length=100, null=True)),
                ("uf", models.CharField(max_length=2, null=True)),
                ("pais", models.CharField(max_length=50, null=True)),
                ("cep", models.CharField(max_length=10, null=True)),
                ("cpf", models.CharField(max_length=11, null=True)),
                ("numero_identidade", models.CharField(max_length=10, null=True)),
                ("uf_identidade", models.CharField(max_length=2, null=True)),
                (
                    "orgao_emissor_identidade",
                    models.CharField(max_length=50, null=True),
                ),
                ("data_emissao_identidade", models.DateField(null=True)),
                ("numero_cns", models.CharField(max_length=15, null=True)),
                (
                    "nome_representante_legal",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "relacionamento_representante_legal",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cpf_representante_legal",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True, null=True)),
                ("descricao", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Medico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, null=True)),
                (
                    "nome_social",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nome_mae", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("Masculino", "Masculino"),
                            ("Feminino", "Feminino"),
                            ("Intersexo", "Intersexo"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("genero", models.CharField(blank=True, max_length=50, null=True)),
                ("data_nascimento", models.DateField(null=True)),
                (
                    "raca",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Branca", "Branca"),
                            ("Preta", "Preta"),
                            ("Parda", "Parda"),
                            ("Amarela", "Amarela"),
                            ("Indígena", "Indígena"),
                            ("Sem Informação", "Sem Informação"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "nacionalidade",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cidade_nascimento",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "uf_nascimento",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                ("data_naturalizacao", models.DateField(blank=True, null=True)),
                (
                    "pais_nascimento",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "numero_passaporte",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "pais_emissao",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("data_emissao", models.DateField(blank=True, null=True)),
                ("data_validade", models.DateField(blank=True, null=True)),
                ("email", models.CharField(max_length=50, null=True)),
                (
                    "tipo_telefone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Residencial", "Residencial"),
                            ("Celular", "Celular"),
                            ("Comercial", "Comercial"),
                            ("Outro", "Outro"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("ddd", models.CharField(blank=True, max_length=3, null=True)),
                ("telefone", models.CharField(max_length=200, null=True)),
                (
                    "tipo_logradouro",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "nome_logradouro",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "numero_logradouro",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "complemento_logradouro",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("bairro", models.CharField(blank=True, max_length=100, null=True)),
                ("cidade", models.CharField(blank=True, max_length=100, null=True)),
                ("uf", models.CharField(blank=True, max_length=2, null=True)),
                ("pais", models.CharField(blank=True, max_length=50, null=True)),
                ("cep", models.CharField(blank=True, max_length=10, null=True)),
                ("cpf", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "numero_identidade",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "uf_identidade",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "orgao_emissor_identidade",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("data_emissao_identidade", models.DateField(blank=True, null=True)),
                ("numero_cns", models.CharField(blank=True, max_length=20, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "especialidade",
                    models.CharField(
                        choices=[
                            ("Cardiologista", "Cardiologista"),
                            ("Psiquiatra", "Psiquiatra"),
                            ("Ortopedista", "Ortopedista"),
                            ("Dermatologista", "Dermatologista"),
                            ("Oftalmologista", "Oftalmologista"),
                            ("Ginecologista", "Ginecologista"),
                            ("Pediatra", "Pediatra"),
                            ("Urologista", "Urologista"),
                            ("Neurologista", "Neurologista"),
                            ("Fisioterapeuta", "Fisioterapeuta"),
                            ("Psicólogo", "Psicólogo"),
                            ("Terapeuta", "Terapeuta"),
                            ("Cirurgião", "Cirurgião"),
                            ("Anestesista", "Anestesista"),
                            ("Radiologista", "Radiologista"),
                            ("Oncologista", "Oncologista"),
                            ("Infectologista", "Infectologista"),
                            ("Outro", "Outro"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("pacientes", models.ManyToManyField(to="accounts.paciente")),
            ],
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(null=True)),
                ("hora", models.TimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Agendada", "Agendada"),
                            ("Realizada", "Realizada"),
                            ("Cancelada", "Cancelada"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("descricao", models.TextField(null=True)),
                ("duracao_estimada", models.DurationField(null=True)),
                (
                    "medico",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.medico",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.paciente",
                    ),
                ),
            ],
        ),
    ]
